# Generated by Django 4.2.4 on 2023-12-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoPath', models.CharField(max_length=120)),
                ('my_array', models.CharField(max_length=50000)),
            ],
        ),
    ]
